apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-persistenceagent
  name: ml-pipeline-persistenceagent
spec:
  selector:
    matchLabels:
      app: ml-pipeline-persistenceagent
  template:
    metadata:
      labels:
        app: ml-pipeline-persistenceagent
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TTL_SECONDS_AFTER_WORKFLOW_FINISH
            value: "86400"
          - name: NUM_WORKERS
            value: "2"
          - name: LOG_LEVEL
            value: "info"
        #image: ghcr.io/kubeflow/kfp-persistence-agent:dummy
        image: registry.redhat.io/rhoai/odh-ml-pipelines-persistenceagent-v2-rhel8@sha256:4e0c858d68f925a307ee53498aa6019563254c5b27f5d7635debc0195db2c5bd
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-persistenceagent
        resources:
          requests:
            cpu: 120m
            memory: 500Mi
        volumeMounts:
          - mountPath: /var/run/secrets/kubeflow/tokens
            name: persistenceagent-sa-token
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   runAsNonRoot: true
        #   runAsUser: 1000
        #   runAsGroup: 0
        #   capabilities:
        #     drop:
        #       - ALL
        securityContext:
          capabilities:
            drop:
              - ALL
          runAsUser: 1000650001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      serviceAccountName: ml-pipeline-persistenceagent
      volumes:
        - name: persistenceagent-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: persistenceagent-sa-token
                  expirationSeconds: 3600
                  audience: pipelines.kubeflow.org
