apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-scheduledworkflow
  name: ml-pipeline-scheduledworkflow
spec:
  selector:
    matchLabels:
      app: ml-pipeline-scheduledworkflow
  template:
    metadata:
      labels:
        app: ml-pipeline-scheduledworkflow
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: ghcr.io/kubeflow/kfp-scheduled-workflow-controller:dummy
      #- image: registry.redhat.io/rhoai/odh-ml-pipelines-scheduledworkflow-v2-rhel8@sha256:99ca5a981184f0dd3f94105172b20494328c5c7a762fb027905e108710b7b5d4
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-scheduledworkflow
        env:
          - name: LOG_LEVEL
            value: "info"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CRON_SCHEDULE_TIMEZONE
            valueFrom:
              configMapKeyRef:
                name: pipeline-install-config
                key: cronScheduleTimezone
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   runAsNonRoot: true
        #   runAsUser: 1000
        #   runAsGroup: 0
        #   capabilities:
        #     drop:
        #       - ALL
        securityContext:
          capabilities:
            drop:
              - ALL
          runAsUser: 1000650001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        volumeMounts:
          - mountPath: /var/run/secrets/kubeflow/tokens
            name: scheduledworkflow-sa-token
      serviceAccountName: ml-pipeline-scheduledworkflow
      volumes:
        - name: scheduledworkflow-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: scheduledworkflow-sa-token
                  expirationSeconds: 3600
                  audience: pipelines.kubeflow.org
