apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql
      containers:
      # - args:
      #   - --datadir
      #   - /var/lib/mysql
      #   - --authentication-policy=mysql_native_password
      #   - --mysql-native-password=ON
      #   - --disable-log-bin
      #   env:
      #   - name: MYSQL_ALLOW_EMPTY_PASSWORD
      #     value: "true"
      #   image: mysql:8.4
      - args:
        - --datadir=/var/lib/mysql
        - --skip-log-bin
        env:
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: "true"
        image: mariadb
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   runAsNonRoot: true
        #   runAsUser: 999
        #   runAsGroup: 999
        #   capabilities:
        #     drop:
        #     - ALL
        securityContext:
          capabilities:
            drop:
              - ALL
          runAsUser: 1000650001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
        resources:
          requests:
            cpu: 100m
            memory: 800Mi
      securityContext:
        #fsGroup: 999
        #fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
