apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-envoy-deployment
  labels:
    component: metadata-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: metadata-envoy
  template:
    metadata:
      labels:
        component: metadata-envoy
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: container
        #image: ghcr.io/kubeflow/kfp-metadata-envoy:dummy
        image: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:b30d60cd458133430d4c92bf84911e03cecd02f60e88a58d1c6c003543cf833a
        ports:
        - name: md-envoy
          containerPort: 9090
        - name: envoy-admin
          containerPort: 9901
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   seccompProfile:
        #     type: RuntimeDefault
        #   runAsNonRoot: true
        #   runAsUser: 1000
        #   runAsGroup: 0
        #   capabilities:
        #     drop:
        #     - ALL
        securityContext:
          capabilities:
            drop:
              - ALL
          runAsUser: 1000650001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
