apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy-agent
  name: proxy-agent
spec:
  selector:
    matchLabels:
      app: proxy-agent
  template:
    metadata:
      labels:
        app: proxy-agent
    spec:
      #hostNetwork: true
      containers:
      #- image: ghcr.io/kubeflow/kfp-inverse-proxy-agent:dummy
      - image: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8@sha256:b30d60cd458133430d4c92bf84911e03cecd02f60e88a58d1c6c003543cf833a
        imagePullPolicy: IfNotPresent
        name: proxy-agent
        securityContext:
          capabilities:
            drop:
              - ALL
          runAsUser: 1000650001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      serviceAccountName: proxy-agent-runner
